to improve
Kamildeeal/Pokemons_APP_React_TS pull request #1
Opened 2024-03-06 21:56 UTC by Kamildeeal

2024-03-08 08:01 UTC, aliberski commented on package.json
> +    "@testing-library/jest-dom": "^5.17.0",
@Kamildeeal testing related libraries should be in `devDependencies`

2024-03-08 08:06 UTC, aliberski requested changes

2024-03-08 08:06 UTC, aliberski commented on package.json
> +    "@types/jest": "^27.5.2",
@Kamildeeal type related libraries should be in `devDependencies`

2024-03-08 08:06 UTC, aliberski commented on src/App.tsx
> +
@Kamildeeal fix formatting. There are too many whitespaces. You can check `prettier` it will automatically format your files

2024-03-08 08:06 UTC, aliberski commented on src/compontents/Favourites.tsx
> +  favourites: string[]; // Zmieniłem typ na string[], ponieważ mamy tylko nazwy pokemonów
@Kamildeeal English only

2024-03-08 08:06 UTC, aliberski commented on src/compontents/Favourites.tsx
> +  remove: any;
@Kamildeeal it's a function so it should be called `onRemove` and add proper types. `(pokemonName: string) => void`

2024-03-08 08:06 UTC, aliberski commented on src/compontents/Main.tsx
> +    const [favorites, setFavorites] = useState<any[]>([]);
@Kamildeeal can you avoid `any` here?

2024-03-08 08:06 UTC, aliberski commented on src/compontents/Main.tsx
> +        const fetchPokemon = async () => {
@Kamildeeal you shouldn't define any functions inside `useEffect` only call them. We can discuss it later

2024-03-11 07:47 UTC, liberskyy commented on src/providers/Pokemon/PokemonProvider.tsx
> +    const getEachPokemon = async (response: any) => {
You should create some interface for the response from the api and use it instead of `any`

2024-03-11 08:08 UTC, liberskyy commented on src/routes/router.tsx
> +    path: "/details/:pokemonName",
You can reuse declared enum `${Screen.Details}/:pokemonName`

2024-03-14 07:40 UTC, aliberski commented on src/screens/Favorites/Favorites.tsx
> +
@Kamildeeal try to avoid big `if` blocks inside JSX. Here you can define a function 
```
const renderContent = () => {
  if (isFavoritesEmpty) {
     return <p>No favourite pokemons added yet.</p>;
  }
  
  return everything else
}
```

2024-03-14 07:48 UTC, aliberski commented on src/screens/Favorites/Favorites.tsx
> +        pokemon.map((pokemon) => (
@Kamildeeal create a separate function `renderPokemon` and pass it to `map`. Also this function should be wrapped in `useCallback` hook. Whenever something is rendered in a loop wrap it in `useCallback` to avoid unnecessary re-renders

2024-03-14 07:48 UTC, aliberski commented on src/screens/Favorites/Favorites.tsx
> +                  {pokemon.abilities.map((ability: any, index: number) => (
@Kamildeeal can you avoid `any` here?

2024-03-14 07:48 UTC, aliberski commented on src/screens/Favorites/Favorites.tsx
> +                {pokemon.stats.map((stat: any, index: number) => (
@Kamildeeal can you avoid any?

2024-03-14 07:48 UTC, aliberski commented on src/screens/Favorites/useFavorites.ts
> +  const getPokemonType = (typeName: string): string => {
@Kamildeeal this is pure function, so you don't need to define it inside the hook. Please move it out

2024-03-14 07:48 UTC, aliberski commented on src/screens/PokemonDetails/PokemonDetails.tsx
> +            {currentPokemon.id < 10
@Kamildeeal create a function for this logic to make it more readable. Don't nest ternary operator ifs. It's much more readable with standard `if` conditions. Also please try to not put a lot of logic inside JSX

2024-03-14 07:48 UTC, aliberski commented on src/screens/PokemonDetails/usePokemonDetails.ts
> +  useEffect(() => {
@Kamildeeal fix formatting. Add whitespace before useEffect and before each function definition

2024-03-14 07:48 UTC, aliberski commented on src/screens/PokemonList/PokemonList.tsx
> +          {loading ? (
@Kamildeeal create `renderContent` function

2024-03-14 07:48 UTC, aliberski commented on src/screens/PokemonList/PokemonList.tsx
> +              .slice(itemOffset, itemOffset + itemsPerPage)
@Kamildeeal this slice should be done in the hook. You can return final data from the hook and just render it on the screen

2024-03-14 07:48 UTC, aliberski commented on src/screens/PokemonList/PokemonList.tsx
> +                      {item.id < 10
@Kamildeeal move this logic to a separate function. You can use this function to add 0 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2024-03-14 07:48 UTC, aliberski commented on src/screens/PokemonList/PokemonList.tsx
> +              .map((item) => (
@Kamildeeal create `renderPokemon` function and wrap it in `useCallback`

2024-03-18 08:14 UTC, aliberski commented on src/compontents/Navbar.tsx
> +    const overlay = document.getElementById("overlay");
@Kamildeeal you shouldn't interact with DOM in react. Never use getElementById. Instead you can create a state like `isMenuOpen` and add certain class to JSX component basing on it

2024-03-18 08:14 UTC, aliberski commented on src/compontents/Navbar.tsx
> +  const [isHamburgerOpen, setIsHamburgerOpen] = useState(false);
@Kamildeeal change it to `isMenuOpen`

2024-03-18 08:17 UTC, aliberski commented on src/compontents/Navbar.tsx
> +  useEffect(() => {
@Kamildeeal create a separate hook in `src/hooks`. Something like here https://stackoverflow.com/a/36862446
It needs to be reusable

2024-03-18 08:18 UTC, aliberski commented on src/screens/PokemonList/usePokemonList.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
@Kamildeeal why do you need to disable eslint here?

2024-03-18 08:19 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
@Kamildeeal why do you need to disable eslint here?

2024-03-18 08:20 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +  const [pokemonData, setPokemonData] = useState<any>([]);
@Kamildeeal can you avoid `any` here?

2024-03-18 08:21 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +      setFavorites(favorites.filter((name) => name !== pokemonName));
@Kamildeeal use callback when you base on previous state. 
```
setFavorites(prevFavorites => prevFavorites.filter((name) => name !== pokemonName)
```

2024-03-18 08:21 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +      setFavorites([...favorites, pokemonName]);
@Kamildeeal same here

2024-03-18 08:21 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +    setFavorites(favorites.filter((name) => name !== pokemonName));
@Kamildeeal base on callback state

2024-03-18 08:22 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +      setFetching(true);
@Kamildeeal `isFetching` and `isLoading` is the same. Remove one of these flags

2024-03-18 08:23 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +          setPokemonData((prevData: object[]) => {
@Kamildeeal can you type it properly? `object` is almost the same as `any`

2024-03-18 08:25 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +  if (item.id < 10) {
@Kamildeeal you probably don't need these conditions at all. Just use `idToString.padStart(3, "0");` and it should work in all cases

2024-03-18 08:26 UTC, aliberski commented on src/screens/Favorites/Favorites.tsx
> +        pokemon.map((displayedPokemon) => renderPokemon(displayedPokemon))
@Kamildeeal 
```
        pokemon.map(renderPokemon)
```

2024-03-27 09:40 UTC, aliberski requested changes

2024-03-27 09:40 UTC, aliberski commented on src/compontents/Navbar.tsx
> +          <span></span>
@Kamildeeal why do you need these empty spans?

2024-03-27 09:40 UTC, aliberski commented on src/compontents/Navbar.tsx
> +          <a className="open-active_a" href="#">
@Kamildeeal please create a component called `Link` instead of repeating the same thing

2024-03-27 09:40 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +  const [url, setUrl] = useState<string>(
@Kamildeeal you don't need this state at all, because you don't use `setUrl`. The url could be a constant

2024-03-27 09:40 UTC, aliberski commented on src/providers/Pokemon/PokemonProvider.tsx
> +      setFavorites(favorites.filter((name) => name !== pokemonName));
@Kamildeeal you didn't change anything here as I see

2024-03-27 18:45 UTC, Kamildeeal commented on src/compontents/Navbar.tsx
> +          <span></span>
I use these spans to create "hamburger menu" look, later after toggle it switch look to "X" button

2024-05-26 13:54 UTC, merged